name: Java CI with Maven

on:
  push:
    paths:
      - src/**
      - pom.xml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B verify
